[package]
name = "pulumi-language-rust"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "server"
path = "./src/server.rs"

[dependencies]
grpc = "*"
grpc-protobuf = "*"
protobuf = "2"

[build-dependencies]
protoc-rust-grpc = "0.8.3"
